"""Session context manager for conversation history.

Manages dataset paths and query history per session.
The agent is stateless, but sessions allow for context continuity.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional
from datetime import datetime


@dataclass
class SessionContext:
    """Context for a single conversation session."""

    session_id: str
    dataset_path: Optional[str] = None
    created_at: datetime = field(default_factory=datetime.utcnow)
    last_activity: datetime = field(default_factory=datetime.utcnow)
    query_history: List[Dict] = field(default_factory=list)
    metadata: Dict = field(default_factory=dict)

    def add_query(self, query: str, generated_code: str, result: str) -> None:
        """Add a query to the session history.

        Args:
            query: The user's natural language query
            generated_code: The code generated by the agent
            result: The result of the execution
        """
        self.query_history.append({
            "query": query,
            "generated_code": generated_code,
            "result": result,
            "timestamp": datetime.utcnow().isoformat(),
        })
        self.last_activity = datetime.utcnow()

    def get_recent_history(self, count: int = 5) -> List[Dict]:
        """Get the most recent queries from history.

        Args:
            count: Number of recent queries to return

        Returns:
            List of query history entries
        """
        return self.query_history[-count:]

    def has_dataset(self) -> bool:
        """Check if the session has a dataset path set."""
        return self.dataset_path is not None and bool(self.dataset_path)


class SessionManager:
    """Manages multiple conversation sessions."""

    def __init__(self, max_sessions: int = 1000, ttl_hours: int = 24):
        """Initialize the session manager.

        Args:
            max_sessions: Maximum number of active sessions to keep
            ttl_hours: Time-to-live for sessions in hours
        """
        self._sessions: Dict[str, SessionContext] = {}
        self.max_sessions = max_sessions
        self.ttl_hours = ttl_hours

    def get_session(self, session_id: str) -> SessionContext:
        """Get or create a session context.

        Args:
            session_id: Unique session identifier

        Returns:
            The session context
        """
        if session_id not in self._sessions:
            self._sessions[session_id] = SessionContext(session_id=session_id)
            self._cleanup_if_needed()
        return self._sessions[session_id]

    def set_dataset_path(self, session_id: str, dataset_path: str) -> None:
        """Set the dataset path for a session.

        Args:
            session_id: Unique session identifier
            dataset_path: Path to the dataset file
        """
        session = self.get_session(session_id)
        session.dataset_path = dataset_path
        session.last_activity = datetime.utcnow()

    def get_dataset_path(self, session_id: str) -> Optional[str]:
        """Get the dataset path for a session.

        Args:
            session_id: Unique session identifier

        Returns:
            The dataset path or None if not set
        """
        if session_id in self._sessions:
            return self._sessions[session_id].dataset_path
        return None

    def add_query_to_history(
        self,
        session_id: str,
        query: str,
        generated_code: str,
        result: str,
    ) -> None:
        """Add a query to the session history.

        Args:
            session_id: Unique session identifier
            query: The user's query
            generated_code: Generated Python code
            result: Execution result
        """
        session = self.get_session(session_id)
        session.add_query(query, generated_code, result)

    def get_history(self, session_id: str, count: int = 5) -> List[Dict]:
        """Get query history for a session.

        Args:
            session_id: Unique session identifier
            count: Number of recent queries to return

        Returns:
            List of query history entries
        """
        if session_id in self._sessions:
            return self._sessions[session_id].get_recent_history(count)
        return []

    def clear_session(self, session_id: str) -> None:
        """Clear a session (remove from storage).

        Args:
            session_id: Unique session identifier
        """
        if session_id in self._sessions:
            del self._sessions[session_id]

    def clear_all(self) -> None:
        """Clear all sessions."""
        self._sessions.clear()

    def list_active_sessions(self) -> List[str]:
        """List all active session IDs.

        Returns:
            List of session IDs
        """
        return list(self._sessions.keys())

    def _cleanup_if_needed(self) -> None:
        """Remove oldest sessions if we exceed max_sessions."""
        if len(self._sessions) <= self.max_sessions:
            return

        # Sort by last_activity and remove oldest
        sorted_sessions = sorted(
            self._sessions.items(),
            key=lambda x: x[1].last_activity,
        )

        # Remove oldest sessions
        to_remove = len(self._sessions) - self.max_sessions + 1
        for session_id, _ in sorted_sessions[:to_remove]:
            del self._sessions[session_id]

    def cleanup_expired(self) -> int:
        """Remove expired sessions based on TTL.

        Returns:
            Number of sessions removed
        """
        from datetime import timedelta

        cutoff = datetime.utcnow() - timedelta(hours=self.ttl_hours)
        expired = [
            sid
            for sid, session in self._sessions.items()
            if session.last_activity < cutoff
        ]

        for sid in expired:
            del self._sessions[sid]

        return len(expired)

    def get_session_count(self) -> int:
        """Get the number of active sessions.

        Returns:
            Number of active sessions
        """
        return len(self._sessions)

    def export_session(self, session_id: str) -> Optional[Dict]:
        """Export a session as a dictionary for serialization.

        Args:
            session_id: Unique session identifier

        Returns:
            Session data as dict or None if not found
        """
        if session_id not in self._sessions:
            return None

        session = self._sessions[session_id]
        return {
            "session_id": session.session_id,
            "dataset_path": session.dataset_path,
            "created_at": session.created_at.isoformat(),
            "last_activity": session.last_activity.isoformat(),
            "query_history": session.query_history,
            "metadata": session.metadata,
        }
