"""Pydantic models for API request/response schemas."""

from typing import Any, Dict, List, Literal, Optional

from pydantic import BaseModel, Field, field_validator


class QueryRequest(BaseModel):
    """Request model for natural language queries."""

    query: str = Field(
        ...,
        description="Natural language query describing the desired data analysis",
        min_length=1,
        max_length=2000,
        examples=["How many rows are in the dataset?", "¿Cuántas filas tiene?"],
    )
    dataset_path: str = Field(
        ...,
        description="Path to the dataset file (CSV, Parquet, etc.)",
        min_length=1,
        examples=["/data/sales.csv", "data/customers.parquet"],
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session ID for conversation context",
    )

    @field_validator("dataset_path")
    @classmethod
    def validate_dataset_path(cls, v: str) -> str:
        """Validate that the dataset path is not empty and has a valid extension."""
        if not v.strip():
            raise ValueError("dataset_path cannot be empty or whitespace")
        # Allow common data file extensions
        valid_extensions = (".csv", ".parquet", ".xlsx", ".xls", ".json", ".tsv")
        if not any(v.lower().endswith(ext) for ext in valid_extensions):
            raise ValueError(
                f"dataset_path must have a valid extension: {valid_extensions}"
            )
        return v.strip()


class QueryResponse(BaseModel):
    """Response model for query results."""

    success: bool = Field(..., description="Whether the query execution succeeded")
    result: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Structured result data (DataFrame, scalar, or figure)",
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if success is False",
    )
    execution_time_ms: int = Field(
        ...,
        description="Execution time in milliseconds",
        ge=0,
    )
    generated_code: Optional[str] = Field(
        default=None,
        description="The Python code generated by the agent",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Session ID for conversation context",
    )


class VisualizationRequest(BaseModel):
    """Request model for visualization generation."""

    query: str = Field(
        ...,
        description="Natural language description of the desired visualization",
        min_length=1,
        max_length=2000,
        examples=["Show a histogram of prices", "Histograma de precios"],
    )
    dataset_path: str = Field(
        ...,
        description="Path to the dataset file",
        min_length=1,
    )
    chart_type: Optional[str] = Field(
        default=None,
        description="Desired chart type (histogram, scatter, bar, line, etc.)",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Optional session ID for conversation context",
    )

    @field_validator("dataset_path")
    @classmethod
    def validate_dataset_path(cls, v: str) -> str:
        """Validate that the dataset path is not empty."""
        if not v.strip():
            raise ValueError("dataset_path cannot be empty or whitespace")
        return v.strip()


class VisualizationResponse(BaseModel):
    """Response model for visualization results."""

    success: bool = Field(..., description="Whether the visualization succeeded")
    image_base64: Optional[str] = Field(
        default=None,
        description="Base64-encoded PNG image of the chart",
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if success is False",
    )
    execution_time_ms: int = Field(
        ...,
        description="Execution time in milliseconds",
        ge=0,
    )
    chart_metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        description="Metadata about the generated chart",
    )
    generated_code: Optional[str] = Field(
        default=None,
        description="The Python code generated by the agent",
    )
    session_id: Optional[str] = Field(
        default=None,
        description="Session ID for conversation context",
    )


class ErrorResponse(BaseModel):
    """Generic error response model."""

    success: bool = Field(default=False)
    error: str = Field(..., description="Error message")
    detail: Optional[str] = Field(default=None, description="Additional error details")


class HealthResponse(BaseModel):
    """Health check response model."""

    status: Literal["healthy", "unhealthy"] = Field(...)
    kernel_status: Literal["ready", "busy", "restarting", "error"] = Field(...)
    sandbox_status: Literal["running", "stopped", "error"] = Field(...)
    timestamp: str = Field(..., description="ISO timestamp of the health check")
